/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.wifimanager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import android.net.wifi.ScanResult;
import android.net.wifi.WifiConfiguration;

@Kroll.proxy(creatableInModule = WifimanagerModule.class)
public class ScanResultProxy extends KrollProxy {
	ScanResult scanResult;
	private String password;

	public ScanResult getScanResult() {
		return this.scanResult;
	}

	public ScanResultProxy(ScanResult scanResult) {
		super();
		this.scanResult = scanResult;
	}

	@Kroll.method
	public String getBSSID() {
		return scanResult.BSSID.replace("\\\"", "");
	}

	@Kroll.method
	public String getSSID() {
		return scanResult.SSID.replace("\\\"", "");
	}

	@Kroll.method
	public int getFrequency() {
		return scanResult.frequency;
	}

	@Kroll.method
	public int getRSSI() {
		return scanResult.level;
	}

	@Kroll.method
	public ScanResultProxy setPassword(String password) {
		this.password = password;
		return this;
	}

	@Kroll.method
	public String getPassword() {
		return password;
	}

	@Kroll.method
	public String getSecurity() {
		return Utils.getScanResultSecurity(scanResult);
	}

	@Kroll.method
	public KrollDict getTimes() {
		KrollDict kd = new KrollDict();
		kd.put("timestamp", scanResult.timestamp);
		return kd;
	}

	@Kroll.method
	public boolean hasWPS() {
		return Utils.supportsWPS(scanResult);
	}

	@Kroll.method
	public String toString() {
		return scanResult.toString();
	}

	@Kroll.method
	public String getApiName() {
		return "ti.wifimanager.ScanResultProxy";
	}

}