/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.wifimanager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import android.net.wifi.WpsInfo;

@Kroll.proxy(creatableInModule = WifimanagerModule.class)
public class WpsInfoProxy extends KrollProxy {
	private WpsInfo wpsInfo;
	private String BSSID;
	private String pin;
	private int setup = 0;

	public WpsInfoProxy() {
		super();
	}

	@Override
	public void handleCreationDict(
			@Kroll.argument(optional = true) KrollDict options) {

		super.handleCreationDict(options);
		wpsInfo = new WpsInfo();
		if (options != null) {
			if (options.containsKeyAndNotNull("BSSID")) {
				BSSID = options.getString("BSSID");
			}
			if (options.containsKeyAndNotNull("pin")) {
				pin = options.getString("pin");
			}

		}

	}

	public WpsInfo getWpsInfo() {
		return wpsInfo;
	}

	@Kroll.method
	public String toString() {
		return wpsInfo.toString();
	}

}